# Generated by Django 5.2.12 on 2026-05-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='horario_abertura',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='horario_fechamento',
            field=models.TimeField(default='18:00'),
        ),
    ]
