# Generated by Django 5.2.12 on 2026-05-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_estabelecimento_horario_abertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('GESTOR', 'Gestor'), ('LAVADOR', 'Lavador')], default='LAVADOR', max_length=20),
        ),
    ]
