# Generated by Django 5.2.12 on 2026-05-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vincular_gestor_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
