# Generated by Django 5.2.12 on 2026-05-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_estabelecimento_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
