# Generated by Django 5.2.12 on 2026-05-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_estabelecimento_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
