# Generated by Django 5.2.12 on 2026-06-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_geo_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='avaliacao_media',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
