# Generated by Django 5.2.12 on 2026-04-16 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracao_estimada_min', models.PositiveIntegerField(help_text='Duração estimada em minutos')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='TagPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Capô, Porta Dianteira Esq', max_length=100)),
                ('categoria', models.CharField(choices=[('frente', 'Frente'), ('lateral_esq', 'Lateral Esquerda'), ('lateral_dir', 'Lateral Direita'), ('traseira', 'Traseira'), ('interior', 'Interior')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('cor', models.CharField(blank=True, default='', max_length=50)),
                ('nome_dono', models.CharField(max_length=150)),
                ('celular_dono', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('PATIO', 'Pátio (Aguardando)'), ('VISTORIA_INICIAL', 'Vistoria Inicial'), ('EM_EXECUCAO', 'Em Execução'), ('LIBERACAO', 'Liberação'), ('FINALIZADO', 'Finalizado'), ('BLOQUEADO_INCIDENTE', 'Bloqueado por Incidente'), ('CANCELADO', 'Cancelado')], default='PATIO', max_length=25)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('laudo_vistoria', models.TextField(blank=True, null=True)),
                ('comentario_lavagem', models.TextField(blank=True, null=True)),
                ('comentario_acabamento', models.TextField(blank=True, null=True)),
                ('vaga_patio', models.CharField(blank=True, max_length=50, null=True)),
                ('horario_inicio', models.DateTimeField(blank=True, null=True)),
                ('horario_lavagem', models.DateTimeField(blank=True, null=True)),
                ('horario_acabamento', models.DateTimeField(blank=True, null=True)),
                ('horario_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='atendimentos.servico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='atendimentos.veiculo')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='MidiaOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='ordens_servico/%Y/%m/%d/')),
                ('momento', models.CharField(choices=[('VISTORIA_GERAL', 'Vistoria Geral'), ('AVARIA_PREVIA', 'Avaria Prévia'), ('EXECUCAO', 'Execução'), ('FINALIZADO', 'Finalizado')], max_length=20)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='atendimentos.ordemservico')),
            ],
            options={
                'verbose_name': 'Mídia de OS',
                'verbose_name_plural': 'Mídias de OS',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='IncidenteOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Relato detalhado do operador')),
                ('foto_url', models.ImageField(help_text='Evidência do dano', upload_to='incidentes/%Y/%m/%d/')),
                ('resolvido', models.BooleanField(default=False, help_text='Controle para liberação pelo Gestor')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='atendimentos.ordemservico')),
                ('tag_peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='atendimentos.tagpeca')),
            ],
        ),
    ]
