# Generated by Django 5.2.12 on 2026-04-05 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracao_estimada_min', models.PositiveIntegerField(help_text='Duração estimada em minutos')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('cor', models.CharField(blank=True, default='', max_length=50)),
                ('nome_dono', models.CharField(max_length=150)),
                ('celular_dono', models.CharField(blank=True, default='', max_length=20)),
                ('ano', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('etapa_atual', models.PositiveSmallIntegerField(choices=[(1, 'Vistoria'), (2, 'Lavagem'), (3, 'Acabamento'), (4, 'Liberação')], default=1)),
                ('horario_inicio', models.DateTimeField(blank=True, null=True)),
                ('horario_lavagem', models.DateTimeField(blank=True, null=True)),
                ('horario_acabamento', models.DateTimeField(blank=True, null=True)),
                ('horario_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('laudo_vistoria', models.TextField(blank=True, default='')),
                ('partes_avaria', models.JSONField(blank=True, default=list)),
                ('checklist_lavagem', models.JSONField(blank=True, default=list, help_text='Lista de itens concluídos na lavagem')),
                ('laudo_lavagem', models.TextField(blank=True, default='')),
                ('laudo_acabamento', models.TextField(blank=True, default='')),
                ('vaga_patio', models.CharField(blank=True, default='', max_length=50)),
                ('notas_entrega', models.TextField(blank=True, default='')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='atendimentos.servico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='atendimentos.veiculo')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='MidiaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='atendimentos/%Y/%m/%d/')),
                ('momento', models.CharField(choices=[('ANTES', 'Antes'), ('DEPOIS', 'Depois')], max_length=10)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='atendimentos.atendimento')),
            ],
            options={
                'verbose_name': 'Mídia de Atendimento',
                'verbose_name_plural': 'Mídias de Atendimento',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
