# Generated by Django 5.2.12 on 2026-04-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='horario_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
