# Generated by Django 5.2.12 on 2026-04-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midiaatendimento',
            options={},
        ),
        migrations.AddField(
            model_name='midiaatendimento',
            name='parte_nome',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
