# Generated by Django 5.2.12 on 2026-04-08 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_atendimento_horario_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('execucao', 'Em Execução'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='atendimentos.atendimento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='MaterialOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidade', models.CharField(max_length=20)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='atendimentos.ordemservico')),
            ],
            options={
                'verbose_name': 'Material da OS',
                'verbose_name_plural': 'Materiais da OS',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EtapaOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('concluida', models.BooleanField(default=False)),
                ('tempo_estimado', models.TimeField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='atendimentos.ordemservico')),
            ],
            options={
                'verbose_name': 'Etapa da OS',
                'verbose_name_plural': 'Etapas da OS',
                'ordering': ['ordem'],
            },
        ),
    ]
