# Generated by Django 5.2.12 on 2026-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_atendimento_horario_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-data_hora']},
        ),
        migrations.AddField(
            model_name='atendimento',
            name='comentario_acabamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='comentario_lavagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='horario_acabamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='horario_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='horario_lavagem',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='laudo_vistoria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='vaga_patio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
