# Generated by Django 5.2.12 on 2026-04-13 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_alter_atendimento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Capô, Porta Dianteira Esq [cite: 60]', max_length=100)),
                ('categoria', models.CharField(choices=[('frente', 'Frente'), ('lateral_esq', 'Lateral Esquerda'), ('lateral_dir', 'Lateral Direita'), ('traseira', 'Traseira'), ('interior', 'Interior')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('incidente', 'Incidente/Bloqueado')], default='agendado', max_length=20),
        ),
        migrations.AlterField(
            model_name='midiaatendimento',
            name='momento',
            field=models.CharField(choices=[('VISTORIA_GERAL', 'Vistoria Geral'), ('AVARIA_PREVIA', 'Avaria Prévia'), ('EXECUCAO', 'Execução'), ('FINALIZADO', 'Finalizado')], max_length=20),
        ),
        migrations.CreateModel(
            name='IncidenteOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Relato detalhado do operador [cite: 63]')),
                ('foto_url', models.ImageField(help_text='Evidência do dano causado [cite: 63]', upload_to='incidentes/%Y/%m/%d/')),
                ('resolvido', models.BooleanField(default=False, help_text='Controle para liberação pelo Gestor [cite: 63]')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='atendimentos.atendimento')),
                ('tag_peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='atendimentos.tagpeca')),
            ],
        ),
    ]
