# Generated by Django 5.2.12 on 2026-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_ordemservico_materialos_etapaos'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='laudo_acabamento',
            field=models.TextField(blank=True, default=''),
        ),
    ]
