# Generated by Django 5.2.12 on 2026-04-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_atendimento_laudo_acabamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='checklist_lavagem',
            field=models.JSONField(blank=True, default=list, help_text='Lista de itens concluídos na lavagem'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='etapa_atual',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Vistoria'), (2, 'Lavagem'), (3, 'Acabamento'), (4, 'Liberação')], default=1),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='horario_acabamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='horario_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='horario_lavagem',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='laudo_lavagem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='laudo_vistoria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='notas_entrega',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='partes_avaria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='vaga_patio',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='midiaatendimento',
            name='parte_nome',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
