# Generated by Django 5.2.12 on 2026-04-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0007_alter_atendimento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='checklist_lavagem',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='laudo_acabamento',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='laudo_lavagem',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='notas_entrega',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='vaga_patio',
        ),
    ]
