# Generated by Django 5.2.12 on 2026-05-02 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PATIO', 'Pátio'), ('VISTORIA_INICIAL', 'Vistoria Inicial'), ('EM_EXECUCAO', 'Em Execução'), ('LIBERACAO', 'Liberação'), ('FINALIZADO', 'Finalizado'), ('BLOQUEADO_INCIDENTE', 'Bloqueado por Incidente'), ('CANCELADO', 'Cancelado')], default='PATIO', max_length=25)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('laudo_vistoria', models.TextField(blank=True, null=True)),
                ('horario_lavagem', models.DateTimeField(blank=True, null=True)),
                ('horario_acabamento', models.DateTimeField(blank=True, null=True)),
                ('comentario_lavagem', models.TextField(blank=True, null=True)),
                ('comentario_acabamento', models.TextField(blank=True, null=True)),
                ('vaga_patio', models.CharField(blank=True, max_length=20, null=True)),
                ('horario_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.estabelecimento')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='MidiaOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='os/')),
                ('momento', models.CharField(max_length=20)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='operacao.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenteOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('foto_url', models.ImageField(upload_to='incidentes/')),
                ('status_anterior_os', models.CharField(choices=[('PATIO', 'Pátio'), ('VISTORIA_INICIAL', 'Vistoria Inicial'), ('EM_EXECUCAO', 'Em Execução'), ('LIBERACAO', 'Liberação'), ('FINALIZADO', 'Finalizado'), ('BLOQUEADO_INCIDENTE', 'Bloqueado por Incidente'), ('CANCELADO', 'Cancelado')], max_length=25)),
                ('resolvido', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('observacoes_resolucao', models.TextField(blank=True, null=True)),
                ('gestor_resolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_resolvidos', to=settings.AUTH_USER_MODEL)),
                ('tag_peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tagpeca')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='operacao.ordemservico')),
            ],
        ),
    ]
