# Generated by Codex on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_alter_ordemservico_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midiaordemservico',
            name='momento',
            field=models.CharField(
                choices=[
                    ('VISTORIA_GERAL', 'Vistoria geral'),
                    ('AVARIA_PREVIA', 'Avaria previa'),
                    ('FINALIZADO', 'Finalizado'),
                    ('EXECUCAO', 'Execucao'),
                    ('ENTRADA', 'Entrada'),
                    ('FINALIZACAO', 'Finalizacao'),
                    ('INCIDENTE', 'Incidente'),
                    ('ACABAMENTO', 'Acabamento'),
                    ('PROCESSO', 'Processo'),
                ],
                max_length=20,
            ),
        ),
    ]
