# Generated by Django 5.2.12 on 2026-05-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_incidenteos_campos_resolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midiaordemservico',
            name='momento',
            field=models.CharField(choices=[('ENTRADA', 'Vistoria de Entrada'), ('FINALIZACAO', 'Entrega / Finalização'), ('PROCESSO', 'Processo / Lavagem'), ('INCIDENTE', 'Registro de Incidente'), ('ACABAMENTO', 'Acabamento / Detalhamento')], max_length=20),
        ),
    ]
