# Generated by Django 5.2.12 on 2026-05-04 01:40
# Editado manualmente: padrão dois passos para UUID único com SQLite (dados pré-existentes).

import uuid
from django.db import migrations, models


def popular_slugs_cancelamento(apps, schema_editor):
    """Gera UUID único para cada OrdemServico existente que ainda não tem slug."""
    OrdemServico = apps.get_model('operacao', 'OrdemServico')
    for os in OrdemServico.objects.filter(slug_cancelamento__isnull=True):
        os.slug_cancelamento = uuid.uuid4()
        os.save(update_fields=['slug_cancelamento'])


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0002_alter_ordemservico_data_hora'),
    ]

    operations = [
        # --- Campos simples sem restrição de unicidade ---
        migrations.AddField(
            model_name='ordemservico',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cancelado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),

        # RF-24 — Passo 1: adiciona slug SEM unique (compatível com rows existentes)
        migrations.AddField(
            model_name='ordemservico',
            name='slug_cancelamento',
            field=models.UUIDField(blank=True, null=True, editable=False),
        ),

        # RF-24 — Passo 2: popula UUID em todas as OS já existentes
        migrations.RunPython(popular_slugs_cancelamento, reverse_code=migrations.RunPython.noop),

        # RF-24 — Passo 3: aplica unique + default agora que todos os valores são únicos
        migrations.AlterField(
            model_name='ordemservico',
            name='slug_cancelamento',
            field=models.UUIDField(default=uuid.uuid4, blank=True, null=True, editable=False, unique=True),
        ),
    ]
