# Generated by Django 5.2.12 on 2026-05-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0003_alter_midiaordemservico_momento'),
        ('operacao', '0003_rf24_campos_cancelamento'),
    ]

    operations = [
    ]
