# Generated by Django 5.2.12 on 2026-05-13 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0004_merge_20260506_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='comentario_acabamento',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='horario_acabamento',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='etapa_atual',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
