# Generated by Django 5.2.12 on 2026-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0005_remove_ordemservico_comentario_acabamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midiaordemservico',
            name='momento',
            field=models.CharField(choices=[('VISTORIA_GERAL', 'Vistoria geral'), ('AVARIA_PREVIA', 'Avaria previa'), ('FINALIZADO', 'Finalizado'), ('EXECUCAO', 'Execucao'), ('ENTRADA', 'Entrada'), ('FINALIZACAO', 'Finalizacao'), ('INCIDENTE', 'Incidente'), ('PROCESSO', 'Processo')], max_length=20),
        ),
    ]
