# Generated by Django 5.2.12 on 2026-06-05 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0006_remove_acabamento_momento_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='avaliacao_estrelas',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
