# Generated by Django 5.2.12 on 2026-06-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0007_ordemservico_avaliacao_estrelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='is_pausado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tempo_acumulado_segundos',
            field=models.IntegerField(default=0),
        ),
    ]
