# Generated by Django 5.2.12 on 2026-06-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0008_ordemservico_is_pausado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='valor_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço congelado do serviço no momento da criação da OS', max_digits=10, null=True),
        ),
    ]
