# Generated by Django 5.2.12 on 2026-04-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('operacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoriaitem',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistoria_items', to='operacao.ordemservico'),
        ),
        migrations.AddField(
            model_name='vistoriaitem',
            name='tag_peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tagpeca'),
        ),
        migrations.AlterUniqueTogether(
            name='vistoriaitem',
            unique_together={('ordem_servico', 'tag_peca')},
        ),
    ]
