# Generated by Django 5.2.12 on 2026-05-04 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_estabelecimento_horario_abertura_and_more'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='accounts.cliente'),
        ),
    ]
