# Generated by Django 5.2.12 on 2026-04-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='celular_dono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='nome_dono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
