# Generated by Django 5.2.12 on 2026-04-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_veiculo_celular_dono_veiculo_nome_dono'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servico',
            table='core_servico',
        ),
    ]
