# Generated by Django 5.2.12 on 2026-05-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_estabelecimento_logo_url_estabelecimento_logo'),
        ('core', '0004_alter_servico_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='accounts.cliente'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(choices=[('BRANCO', 'Branco'), ('PRETO', 'Preto'), ('CINZA', 'Cinza'), ('PRATA', 'Prata'), ('VERMELHO', 'Vermelho'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30),
        ),
    ]
