/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/estabelecimento/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Endpoint para o Gestor consultar e atualizar dados do seu estabelecimento. */
        get: operations["auth_estabelecimento_me_retrieve"];
        /** @description Endpoint para o Gestor consultar e atualizar dados do seu estabelecimento. */
        put: operations["auth_estabelecimento_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Endpoint para o Gestor consultar e atualizar dados do seu estabelecimento. */
        patch: operations["auth_estabelecimento_me_partial_update"];
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/meu_perfil/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Endpoint para o usuário logado consultar seu próprio perfil */
        get: operations["auth_meu_perfil_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/registro-cliente/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description RF-25: Cadastro público de perfil Cliente. Username é auto-derivado do email.
         *     Após criar, linka retroativamente veículos com o mesmo celular_dono.
         */
        post: operations["auth_registro_cliente_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cliente/agendamentos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cliente_agendamentos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cliente/auth/setup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cliente_auth_setup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cliente/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cliente_auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cliente/painel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description RF-25: Painel B2C filtrado por Veiculo.cliente, com reparo por telefone normalizado. */
        get: operations["cliente_painel_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cliente/perfil/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cliente_perfil_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["cliente_perfil_partial_update"];
        trace?: never;
    };
    "/api/cliente/veiculos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cliente_veiculos_list"];
        put?: never;
        post: operations["cliente_veiculos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cliente/veiculos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cliente_veiculos_retrieve"];
        put: operations["cliente_veiculos_update"];
        post?: never;
        delete: operations["cliente_veiculos_destroy"];
        options?: never;
        head?: never;
        patch: operations["cliente_veiculos_partial_update"];
        trace?: never;
    };
    "/api/gestao/estabelecimento/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/gestao/estabelecimento/ - Retorna dados do estabelecimento
         *     PATCH /api/gestao/estabelecimento/ - Atualiza dados do estabelecimento
         */
        get: operations["gestao_estabelecimento_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description GET /api/gestao/estabelecimento/ - Retorna dados do estabelecimento
         *     PATCH /api/gestao/estabelecimento/ - Atualiza dados do estabelecimento
         */
        patch: operations["gestao_estabelecimento_partial_update"];
        trace?: never;
    };
    "/api/gestao/financeiro/resumo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/gestao/financeiro/resumo/
         *     RF-32: Painel Financeiro Simples
         */
        get: operations["gestao_financeiro_resumo_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gestao/funcionarios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/gestao/funcionarios/ - Lista funcionários do estabelecimento
         *     POST /api/gestao/funcionarios/ - Cadastra novo funcionário
         */
        get: operations["gestao_funcionarios_retrieve"];
        put?: never;
        /**
         * @description GET /api/gestao/funcionarios/ - Lista funcionários do estabelecimento
         *     POST /api/gestao/funcionarios/ - Cadastra novo funcionário
         */
        post: operations["gestao_funcionarios_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gestao/funcionarios/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description PATCH /api/gestao/funcionarios/<id>/ - Atualiza dados do funcionário (Incluindo Status) */
        patch: operations["gestao_funcionarios_partial_update"];
        trace?: never;
    };
    "/api/gestao/gestor/dashboard/eficiencia-equipe/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/gestao/gestor/dashboard/eficiencia-equipe
         *     RF-20: Relatório de Eficiência da Equipe
         */
        get: operations["gestao_gestor_dashboard_eficiencia_equipe_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gestao/gestor/dashboard/indicadores/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/gestao/gestor/dashboard/indicadores
         *     RF-19: Dashboard Executivo Básico
         */
        get: operations["gestao_gestor_dashboard_indicadores_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gestao/incidentes/{id}/comparativo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description RF-31: GET /api/gestao/incidentes/{id}/comparativo/. */
        get: operations["gestao_incidentes_comparativo_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gestao/servicos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["gestao_servicos_list"];
        put?: never;
        post: operations["gestao_servicos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gestao/servicos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["gestao_servicos_retrieve"];
        put: operations["gestao_servicos_update"];
        post?: never;
        /** @description Soft Delete - marca is_active=False em vez de remover */
        delete: operations["gestao_servicos_destroy"];
        options?: never;
        head?: never;
        patch: operations["gestao_servicos_partial_update"];
        trace?: never;
    };
    "/api/gestao/tags-peca/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD de tags de peça do estabelecimento do usuário.
         *
         *     Leitura (list/retrieve): qualquer usuário autenticado com vínculo.
         *     Escrita (create/update/delete): apenas gestores.
         */
        get: operations["gestao_tags_peca_list"];
        put?: never;
        /**
         * @description CRUD de tags de peça do estabelecimento do usuário.
         *
         *     Leitura (list/retrieve): qualquer usuário autenticado com vínculo.
         *     Escrita (create/update/delete): apenas gestores.
         */
        post: operations["gestao_tags_peca_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gestao/tags-peca/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD de tags de peça do estabelecimento do usuário.
         *
         *     Leitura (list/retrieve): qualquer usuário autenticado com vínculo.
         *     Escrita (create/update/delete): apenas gestores.
         */
        get: operations["gestao_tags_peca_retrieve"];
        /**
         * @description CRUD de tags de peça do estabelecimento do usuário.
         *
         *     Leitura (list/retrieve): qualquer usuário autenticado com vínculo.
         *     Escrita (create/update/delete): apenas gestores.
         */
        put: operations["gestao_tags_peca_update"];
        post?: never;
        /**
         * @description CRUD de tags de peça do estabelecimento do usuário.
         *
         *     Leitura (list/retrieve): qualquer usuário autenticado com vínculo.
         *     Escrita (create/update/delete): apenas gestores.
         */
        delete: operations["gestao_tags_peca_destroy"];
        options?: never;
        head?: never;
        /**
         * @description CRUD de tags de peça do estabelecimento do usuário.
         *
         *     Leitura (list/retrieve): qualquer usuário autenticado com vínculo.
         *     Escrita (create/update/delete): apenas gestores.
         */
        patch: operations["gestao_tags_peca_partial_update"];
        trace?: never;
    };
    "/api/incidentes-os/{id}/auditoria/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["incidentes_os_auditoria_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidentes-os/{id}/resolver/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["incidentes_os_resolver_partial_update"];
        trace?: never;
    };
    "/api/incidentes-os/pendentes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["incidentes_os_pendentes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/ordens-servico/{id}/ */
        get: operations["ordens_servico_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/{id}/avancar-etapa/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description PATCH /api/ordens-servico/{id}/avancar-etapa/
         *     Endpoint unificado para transições da esteira.
         */
        patch: operations["ordens_servico_avancar_etapa_partial_update"];
        trace?: never;
    };
    "/api/ordens-servico/{id}/finalizar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description PATCH /api/ordens-servico/{id}/finalizar/
         *     Finaliza a OS na etapa 4 (Liberação) validando fotos FINALIZADO e vaga.
         */
        patch: operations["ordens_servico_finalizar_partial_update"];
        trace?: never;
    };
    "/api/ordens-servico/{id}/fotos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/ordens-servico/{id}/fotos/ */
        post: operations["ordens_servico_fotos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/{id}/incidente/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Endpoint para o operador relatar um dano e travar a OS. */
        post: operations["ordens_servico_incidente_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/entradas-recentes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/ordens-servico/entradas-recentes/ — Últimas entradas no pátio para o Dashboard. */
        get: operations["ordens_servico_entradas_recentes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/hoje/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ordens_servico_hoje_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/horarios-livres/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description RF-22: Consulta de horários para o Funcionário (Mobile).
         *     Utiliza o mesmo motor de disponibilidade do Cliente.
         */
        get: operations["ordens_servico_horarios_livres_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/kanban/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description RF-14: GET /api/ordens-servico/kanban/ — OS operacionais agrupadas por coluna. */
        get: operations["ordens_servico_kanban_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/novo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/ordens-servico/ */
        post: operations["ordens_servico_novo_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/publico/agendamento/checkout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ordens_servico_publico_agendamento_checkout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/servicos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ordens_servico_servicos_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/tags-peca/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ordens_servico_tags_peca_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ordens-servico/tags-peca/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ordens_servico_tags_peca_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publico/agendamento/disponibilidade/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description RF-22: Retorna horários disponíveis para agendamento.
         *     Consome o Motor de Disponibilidade para evitar overbooking.
         */
        get: operations["publico_agendamento_disponibilidade_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publico/agendamento/ordens-servico/{slug}/cancelar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description RF-24: PATCH /api/publico/agendamento/ordens-servico/{slug}/cancelar/
         *     Endpoint público — cliente cancela agendamento via UUID (RF-24.3).
         *     RNF-03: Resposta mínima, sem dados sensíveis do estabelecimento ou funcionários.
         */
        patch: operations["publico_agendamento_ordens_servico_cancelar_partial_update"];
        trace?: never;
    };
    "/api/publico/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publico_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publico/auth/setup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publico_auth_setup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publico/auth/verificacao/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publico_auth_verificacao_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publico/auth/whatsapp/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publico_auth_whatsapp_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publico/estabelecimento/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description RF-21: Endpoint público (sem autenticação) que retorna os dados básicos
         *     de um Estabelecimento e seus serviços ativos via slug.
         */
        get: operations["publico_estabelecimento_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publico/estabelecimentos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description RF-28: GET /api/publico/estabelecimentos/
         *     Lista pública de estabelecimentos ativos com geolocalização para o mapa B2C.
         */
        get: operations["publico_estabelecimentos_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/publico/historico/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description RF-25: Painel B2C filtrado por Veiculo.cliente, com reparo por telefone normalizado. */
        get: operations["publico_historico_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shared/historico/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description RF-31: GET /api/shared/historico/. */
        get: operations["shared_historico_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shared/historico/{id}/galeria/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description RF-31: GET /api/shared/historico/{id}/galeria/. */
        get: operations["shared_historico_galeria_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `GESTOR` - Gestor
         *     * `LAVADOR` - Lavador
         * @enum {string}
         */
        CargoEnum: "GESTOR" | "LAVADOR";
        /**
         * @description * `INTERNO` - Interno
         *     * `EXTERNO` - Externo
         * @enum {string}
         */
        CategoriaEnum: "INTERNO" | "EXTERNO";
        Cliente: {
            readonly id: number;
            name: string;
            /** Format: email */
            email?: string;
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            username?: string;
            password?: string;
            telefone_whatsapp?: string;
            endereco_padrao?: string;
        };
        ClienteVeiculo: {
            readonly id: number;
            placa: string;
            marca: string;
            modelo: string;
            cor: string;
        };
        Estabelecimento: {
            readonly id: number;
            nome_fantasia: string;
            cnpj: string;
            endereco_completo: string;
            is_active?: boolean;
            slug?: string | null;
            /** Format: uri */
            logo?: string | null;
            readonly logo_url: string;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
        };
        /**
         * @description RF-28: Serializer para o mapa B2C. Expõe apenas os campos necessários
         *     para renderizar os pins e o Drawer de resumo do estabelecimento.
         */
        EstabelecimentoMapa: {
            readonly id: number;
            nome_fantasia: string;
            slug?: string | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
            readonly logo: string;
            endereco_completo: string;
        };
        /**
         * @description Exposição pública e segura do Estabelecimento para o Portal de Autoagendamento.
         *     CA-03: cnpj, faturamento e dados do gestor são omitidos por design (não incluídos em fields).
         *     CA-02: servicos filtrados para is_active=True via ServicoPublicoSerializer.
         */
        EstabelecimentoPublico: {
            readonly id: number;
            nome_fantasia: string;
            endereco_completo: string;
            readonly logo_url: string;
            readonly servicos: string;
            slug?: string | null;
        };
        /** @description Serializer restrito para atualização de configurações pelo Gestor. */
        EstabelecimentoUpdate: {
            nome_fantasia: string;
            cnpj: string;
            endereco_completo: string;
            readonly slug: string | null;
            /** Format: uri */
            logo?: string | null;
            readonly logo_url: string;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
        };
        Funcionario: {
            readonly id: number;
            name: string;
            /** Format: email */
            email?: string;
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            username: string;
            password?: string;
            estabelecimento?: number;
            /** @default LAVADOR */
            cargo: components["schemas"]["CargoEnum"];
            /**
             * Ativo
             * @description Indica que o usuário será tratado como ativo. Ao invés de excluir contas de usuário, desmarque isso.
             */
            is_active?: boolean;
            /**
             * Último login
             * Format: date-time
             */
            readonly last_login: string | null;
            /**
             * Data de registro
             * Format: date-time
             */
            readonly date_joined: string;
        };
        IncidentePendente: {
            readonly id: number;
            readonly ordem_servico_id: number;
            readonly status_ordem_servico: string;
            readonly placa: string;
            readonly modelo: string;
            readonly servico: string;
            readonly tag_peca: string;
            descricao: string;
            readonly foto_url: string;
            /** Format: date-time */
            readonly data_registro: string;
        };
        PatchedClienteVeiculo: {
            readonly id?: number;
            placa?: string;
            marca?: string;
            modelo?: string;
            cor?: string;
        };
        /** @description Serializer restrito para atualização de configurações pelo Gestor. */
        PatchedEstabelecimentoUpdate: {
            nome_fantasia?: string;
            cnpj?: string;
            endereco_completo?: string;
            readonly slug?: string | null;
            /** Format: uri */
            logo?: string | null;
            readonly logo_url?: string;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
        };
        PatchedIncidentePendente: {
            readonly id?: number;
            readonly ordem_servico_id?: number;
            readonly status_ordem_servico?: string;
            readonly placa?: string;
            readonly modelo?: string;
            readonly servico?: string;
            readonly tag_peca?: string;
            descricao?: string;
            readonly foto_url?: string;
            /** Format: date-time */
            readonly data_registro?: string;
        };
        PatchedServico: {
            readonly id?: number;
            nome?: string;
            /** Format: decimal */
            preco?: string;
            /**
             * Format: int64
             * @description Tempo médio em minutos
             */
            duracao_estimada_minutos?: number;
            is_active?: boolean;
            readonly estabelecimento?: number;
        };
        PatchedTagPeca: {
            readonly id?: number;
            nome?: string;
            categoria?: components["schemas"]["CategoriaEnum"];
            readonly estabelecimento?: number;
        };
        Servico: {
            readonly id: number;
            nome: string;
            /** Format: decimal */
            preco: string;
            /**
             * Format: int64
             * @description Tempo médio em minutos
             */
            duracao_estimada_minutos: number;
            is_active?: boolean;
            readonly estabelecimento: number;
        };
        TagPeca: {
            readonly id: number;
            nome: string;
            categoria: components["schemas"]["CategoriaEnum"];
            readonly estabelecimento: number;
        };
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_estabelecimento_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Estabelecimento"];
                };
            };
        };
    };
    auth_estabelecimento_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstabelecimentoUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["EstabelecimentoUpdate"];
                "multipart/form-data": components["schemas"]["EstabelecimentoUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstabelecimentoUpdate"];
                };
            };
        };
    };
    auth_estabelecimento_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEstabelecimentoUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEstabelecimentoUpdate"];
                "multipart/form-data": components["schemas"]["PatchedEstabelecimentoUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstabelecimentoUpdate"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_meu_perfil_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Funcionario"];
                "application/x-www-form-urlencoded": components["schemas"]["Funcionario"];
                "multipart/form-data": components["schemas"]["Funcionario"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Funcionario"];
                };
            };
        };
    };
    auth_registro_cliente_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cliente"];
                "application/x-www-form-urlencoded": components["schemas"]["Cliente"];
                "multipart/form-data": components["schemas"]["Cliente"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cliente"];
                };
            };
        };
    };
    cliente_agendamentos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cliente_auth_setup_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cliente_auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cliente_painel_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cliente_perfil_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cliente_perfil_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cliente_veiculos_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteVeiculo"][];
                };
            };
        };
    };
    cliente_veiculos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteVeiculo"];
                "application/x-www-form-urlencoded": components["schemas"]["ClienteVeiculo"];
                "multipart/form-data": components["schemas"]["ClienteVeiculo"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteVeiculo"];
                };
            };
        };
    };
    cliente_veiculos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteVeiculo"];
                };
            };
        };
    };
    cliente_veiculos_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteVeiculo"];
                "application/x-www-form-urlencoded": components["schemas"]["ClienteVeiculo"];
                "multipart/form-data": components["schemas"]["ClienteVeiculo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteVeiculo"];
                };
            };
        };
    };
    cliente_veiculos_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cliente_veiculos_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedClienteVeiculo"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedClienteVeiculo"];
                "multipart/form-data": components["schemas"]["PatchedClienteVeiculo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteVeiculo"];
                };
            };
        };
    };
    gestao_estabelecimento_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestao_estabelecimento_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestao_financeiro_resumo_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestao_funcionarios_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestao_funcionarios_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestao_funcionarios_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestao_gestor_dashboard_eficiencia_equipe_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestao_gestor_dashboard_indicadores_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestao_incidentes_comparativo_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestao_servicos_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servico"][];
                };
            };
        };
    };
    gestao_servicos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Servico"];
                "application/x-www-form-urlencoded": components["schemas"]["Servico"];
                "multipart/form-data": components["schemas"]["Servico"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servico"];
                };
            };
        };
    };
    gestao_servicos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servico"];
                };
            };
        };
    };
    gestao_servicos_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Servico"];
                "application/x-www-form-urlencoded": components["schemas"]["Servico"];
                "multipart/form-data": components["schemas"]["Servico"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servico"];
                };
            };
        };
    };
    gestao_servicos_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestao_servicos_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedServico"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedServico"];
                "multipart/form-data": components["schemas"]["PatchedServico"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servico"];
                };
            };
        };
    };
    gestao_tags_peca_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPeca"][];
                };
            };
        };
    };
    gestao_tags_peca_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagPeca"];
                "application/x-www-form-urlencoded": components["schemas"]["TagPeca"];
                "multipart/form-data": components["schemas"]["TagPeca"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPeca"];
                };
            };
        };
    };
    gestao_tags_peca_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPeca"];
                };
            };
        };
    };
    gestao_tags_peca_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagPeca"];
                "application/x-www-form-urlencoded": components["schemas"]["TagPeca"];
                "multipart/form-data": components["schemas"]["TagPeca"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPeca"];
                };
            };
        };
    };
    gestao_tags_peca_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gestao_tags_peca_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTagPeca"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTagPeca"];
                "multipart/form-data": components["schemas"]["PatchedTagPeca"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPeca"];
                };
            };
        };
    };
    incidentes_os_auditoria_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentePendente"];
                };
            };
        };
    };
    incidentes_os_resolver_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedIncidentePendente"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedIncidentePendente"];
                "multipart/form-data": components["schemas"]["PatchedIncidentePendente"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentePendente"];
                };
            };
        };
    };
    incidentes_os_pendentes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentePendente"];
                };
            };
        };
    };
    ordens_servico_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_avancar_etapa_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_finalizar_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_fotos_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_incidente_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_entradas_recentes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_hoje_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_horarios_livres_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_kanban_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_novo_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_publico_agendamento_checkout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_servicos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ordens_servico_tags_peca_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPeca"][];
                };
            };
        };
    };
    ordens_servico_tags_peca_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este tag peca. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPeca"];
                };
            };
        };
    };
    publico_agendamento_disponibilidade_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publico_agendamento_ordens_servico_cancelar_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publico_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publico_auth_setup_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publico_auth_verificacao_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publico_auth_whatsapp_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publico_estabelecimento_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstabelecimentoPublico"];
                };
            };
        };
    };
    publico_estabelecimentos_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstabelecimentoMapa"][];
                };
            };
        };
    };
    publico_historico_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shared_historico_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shared_historico_galeria_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
